# https://lightning.ai/docs/pytorch/stable/common/trainer.html

_target_: lightning.pytorch.trainer.Trainer
min_epochs: 1
max_epochs: 10
check_val_every_n_epoch: 1
deterministic: False
default_root_dir: ${paths.output_dir}
