# https://lightning.ai/docs/pytorch/stable/common/trainer.html

defaults:
  - logger: logger
  - callbacks: callbacks

_target_: lightning.pytorch.trainer.Trainer
logger:
  - ${logger.csv}
  - ${logger.mlflow}
callbacks:
  - ${callbacks.early_stopping}
  - ${callbacks.model_checkpoint}
  - ${callbacks.rich_progress_bar}
  - ${callbacks.rich_model_summary}
min_epochs: 1
max_epochs: 10
deterministic: null
default_root_dir: ${paths.output_dir}
