[tool.poetry]
name = "dl-template"
version = "0.0.1"
description = "A template for deep learning projects, using PyTorch Lightning and Hydra."
authors = ["miguelbpgh <mbpereira94@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
ipykernel = "^6.29.5"
pytest = "^8.3.2"
numpy = "<2"
pandas = "^2.2.2"
scipy = "^1.14.0"
sympy = "^1.13.1"
networkx = "^3.3"

[tool.poetry.group.dev.dependencies]
statsmodels = "^0.14.2"
matplotlib = "^3.9.1.post1"
seaborn = "^0.13.2"
altair = "^5.4.0"
cvxpy = "^1.5.2"
scikit-learn = "^1.5.1"
lightgbm = "^4.5.0"
xgboost = "^2.1.1"
catboost = "^1.2.5"
optuna = "^3.6.1"
mlflow = "^2.15.1"
tqdm = "^4.66.5"
psutil = "^6.0.0"
loguru = "^0.7.2"
codetiming = "^1.4.0"
joblib = "^1.4.2"
numba = "^0.60.0"
tabulate = "^0.9.0"
hydra-core = "^1.3.2"
pyarrow = "^17.0.0"
missingno = "^0.5.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
