[tool.poetry]
name = "dl-template"
version = "0.0.1"
description = "A template for deep learning projects, using PyTorch Lightning and Hydra."
authors = ["miguelbpgh <mbpereira94@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = "^3.10"
ipykernel = "*"
pytest = "*"
numpy = "<2"
pandas = "*"
scipy = "*"
sympy = "*"
networkx = "*"

[tool.poetry.group.dev.dependencies]
statsmodels = "*"
matplotlib = "*"
seaborn = "*"
altair = "*"
cvxpy = "*"
scikit-learn = "*"
lightgbm = "*"
xgboost = "*"
catboost = "*"
optuna = "*"
mlflow = "*"
tqdm = "*"
psutil = "*"
loguru = "*"
codetiming = "*"
joblib = "*"
numba = "*"
tabulate = "*"
hydra-core = "*"
pyarrow = "*"
missingno = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
