[tool.poetry]
name = "deep-learning-template"
version = "0.0.1"
description = "A template for deep learning projects, using PyTorch Lightning and Hydra."
authors = ["Miguel Pereira <miguel.b.per@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = "^3.10"
ipykernel = "*"
pytest = "*"
numpy = "<2"
pandas = "*"
scipy = "*"
sympy = "*"
networkx = "*"
statsmodels = "*"
matplotlib = "*"
seaborn = "*"
altair = "*"
cvxpy = "*"
scikit-learn = "*"
lightgbm = "*"
xgboost = "*"
catboost = "*"
torch = { version = "*", source = "pytorch" }
torchvision = { version = "*", source = "pytorch" }
torchaudio = { version = "*", source = "pytorch" }
lightning = "*"
torchmetrics = "*"
tensorboard = "*"
optuna = "*"
mlflow = "*"
tqdm = "*"
psutil = "*"
loguru = "*"
codetiming = "*"
joblib = "*"
numba = "*"
tabulate = "*"
rich = "*"
pre-commit = "*"
omegaconf = "*"
hydra-core = "*"
hydra-optuna-sweeper = "*"
hydra_colorlog = "*"
pyarrow = "*"
missingno = "*"
transformers = "*"
scikit-image = "*"
opencv-python = "*"
pillow = "*"
albumentations = "*"
timm = "*"
segmentation-models-pytorch = "*"
nltk = "^3.9.1"
rootutils = "^1.0.7"
pytest-cov = "^5.0.0"

[[tool.poetry.source]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cu124"
priority = "explicit"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
