# https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.loggers.mlflow.html

mlflow:
  _target_: lightning.pytorch.loggers.mlflow.MLFlowLogger
  tracking_uri: ${paths.log_dir}/mlflow/mlruns
  log_model: true

  experiment_name: mlflow_experiment
  run_name: null
  tags: null
