# https://hydra.cc/docs/plugins/colorlog/#internaldocs-banner
defaults:
  - override job_logging: colorlog
  - override hydra_logging: colorlog

# https://hydra.cc/docs/configure_hydra/workdir/
run:
  dir: ${paths.log_dir}/${task_name}/runs/${now:%Y-%m-%d}_${now:%H-%M-%S}
sweep:
  dir: ${paths.log_dir}/${task_name}/multiruns/${now:%Y-%m-%d}_${now:%H-%M-%S}
  subdir: ${hydra.job.num}

# Incorporates fix from https://github.com/facebookresearch/hydra/pull/2242
job_logging:
  handlers:
    file:
      filename: ${hydra.runtime.output_dir}/${task_name}.log
