# https://hydra.cc/docs/plugins/colorlog/#internaldocs-banner
defaults:
  - override job_logging: colorlog
  - override hydra_logging: colorlog

job:
  name: ${experiment_name}

# https://hydra.cc/docs/configure_hydra/workdir/
run:
  dir: ${paths.log_dir}/${hydra.job.name}/runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
sweep:
  dir: ${paths.log_dir}/${hydra.job.name}/multiruns/${now:%Y-%m-%d}/${now:%H-%M-%S}
  subdir: ${hydra.job.num}

# Add fix from https://github.com/facebookresearch/hydra/pull/2242 while there isn't a new release
job_logging:
  handlers:
    file:
      filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log
