_target_: dltemplate.model.model.Model
net:
  _target_: dltemplate.model.resnet.ResNet
  num_classes: 10
loss_fn:
  _target_: torch.nn.CrossEntropyLoss
optimizer:
  _partial_: true
  _target_: torch.optim.Adam
scheduler:
  _partial_: true
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  mode: min
  factor: 0.1
  patience: 10
metric_collection:
  _target_: torchmetrics.MetricCollection
  metrics:
    - _target_: torchmetrics.classification.Accuracy
      task: multiclass
      num_classes: ${model.net.num_classes}
      average: micro
    - _target_: torchmetrics.classification.F1Score
      task: multiclass
      num_classes: ${model.net.num_classes}
      average: macro
    - _target_: torchmetrics.classification.Recall
      task: multiclass
      num_classes: ${model.net.num_classes}
      average: macro
    - _target_: torchmetrics.classification.Precision
      task: multiclass
      num_classes: ${model.net.num_classes}
      average: macro
