_target_: src.model.model.Model
model:
  _target_: torch.nn.Identity
loss_fn:
  _target_: torch.nn.CrossEntropyLoss
optimizer:
  _partial_: true
  _target_: torch.optim.Adam
scheduler: null
metric_collection:
  _target_: torchmetrics.MetricCollection
  metrics: []
