_target_: src.model.model.Model
model:
  _target_: src.model.resnet.ResNet
loss_fn:
  _target_: torch.nn.CrossEntropyLoss
optimizer:
  _partial_: true
  _target_: torch.optim.Adam
scheduler: null
metric_collection:
  _target_: torchmetrics.MetricCollection
  metrics:
    - ${metrics.accuracy}
    - ${metrics.f1_score}
    - ${metrics.precision}
    - ${metrics.recall}
