# csv logger built in lightning
# https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.loggers.csv_logs.html

csv:
  _target_: lightning.pytorch.loggers.csv_logs.CSVLogger
  save_dir: "${paths.output_dir}"
  name: "csv"
  prefix: ""
