# https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.loggers.mlflow.html

mlflow:
  _target_: lightning.pytorch.loggers.mlflow.MLFlowLogger
  tracking_uri: ${paths.log_dir}/mlflow/mlruns # run `mlflow ui` command inside the `logs/mlflow/` dir to open the UI
  # save_dir: "./mlruns"
