# https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.loggers.tensorboard.html

tensorboard:
  _target_: lightning.pytorch.loggers.tensorboard.TensorBoardLogger
  save_dir: ${paths.output_dir}/tensorboard/
  name: null
