# This file should list all available callbacks
# The callbacks in use are specified in the trainer config

defaults:
  - early_stopping
  - model_checkpoint
  - rich_model_summary
  - rich_progress_bar
