defaults:
  - _self_
  - datamodule: null
  - debug: null
  - experiment: null
  - hpo: null
  - hydra: hydra
  - model: null
  - paths: paths
  - trainer: trainer

experiment_name: null
evaluate: null
ckpt_path: null
seed: null
monitor: null
mode: null
