# @package _global_

defaults:
  - _self_
  - datamodule: mnist
  - model: mnist
  - callbacks: default
  - logger: default
  - trainer: default
  - paths: default
  - hydra: default

  - experiment: null
  - hparams_search: null
  - debug: null

task_name: "train"
train: True
eval: True
ckpt_path: null
seed: null

metric: "val/acc"
mode: "max"
