# https://lightning.ai/docs/torchmetrics/stable/classification/accuracy.html

accuracy:
  _target_: torchmetrics.classification.Accuracy
  task: multiclass
  num_classes: ${model.model.num_classes}
  average: micro
