# https://lightning.ai/docs/torchmetrics/stable/classification/f1_score.html

f1_score:
  _target_: torchmetrics.classification.F1Score
  task: multiclass
  num_classes: ${model.model.num_classes}
  average: macro
