# https://lightning.ai/docs/torchmetrics/stable/classification/precision.html

precision:
  _target_: torchmetrics.classification.Precision
  task: multiclass
  num_classes: ${model.net.num_classes}
  average: macro
