# https://lightning.ai/docs/torchmetrics/stable/classification/recall.html

recall:
  _target_: torchmetrics.classification.Recall
  task: multiclass
  num_classes: ${model.net.num_classes}
  average: macro
