# @package _global_

data:
  num_workers: 0
  pin_memory: false

# https://hydra.cc/docs/tutorials/basic/running_your_app/logging/
hydra:
  job_logging:
    root:
      level: DEBUG
  verbose: true

trainer:
  logger: null
  callbacks: null
  max_epochs: 1
  accelerator: cpu
  devices: 1
  detect_anomaly: true

experiment_name: "debug"
