# example hyperparameter optimization of some experiment with Optuna:
# python train.py -m hpo=mnist experiment=example

defaults:
  - override /hydra/sweeper: optuna

# https://hydra.cc/docs/1.1/plugins/optuna_sweeper/
# https://optuna.readthedocs.io/en/stable/reference/generated/optuna.study.create_study.html#optuna.study.create_study
hydra:
  mode: "MULTIRUN"
  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    storage: null
    study_name: null
    n_jobs: 1
    direction: ${mode}imize
    n_trials: 20
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 0
      n_startup_trials: 10
    params:
      model.optimizer.lr: interval(0.0001, 0.1)
